version: '2'

services:
  realtime-object-sync:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: realtime-object-sync
    tty: true
    volumes:
      - ../server/config:/usr/src/app/config
    restart: always
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=www.example.com"
      - "VIRTUAL_PORT=80"
#      - "VIRTUAL_PROTO=https"
      - "LETSENCRYPT_HOST=www.example.com"
      - "LETSENCRYPT_EMAIL=inquiry@example.com"
      - "LETSENCRYPT_TEST=false"
    networks:
      docker-nginx-proxy_front:
        ipv4_address: 192.168.1.20

networks:
  docker-nginx-proxy_front:
    external: true

