version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    tty: false
    privileged: true
    environment:
      - "ENABLE_IPV6=true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - nginx-conf:/etc/nginx/conf.d/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
#    network_mode: host
    networks:
      front:
        ipv4_address: 192.168.1.2
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-letsencrypt
    restart: always
    tty: false
    privileged: true
    environment:
      - "NGINX_PROXY_CONTAINER=proxy-nginx"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      front:
        ipv4_address: 192.168.1.3
volumes:
  vhost:
  html:
  dhparam:
  certs:
    driver_opts:
      type: none
      device: $PWD/certs
      o: bind
  nginx-conf:
    driver_opts:
      type: none
      device: $PWD/config/nginx-conf.d
      o: bind
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
